AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance

Parameters:
  SSHLocation:
    Description: IP for SSH access
    Type: String
    Default: 58.11.11.14/32
  NvmUrl:
    Description: URL for nvm install
    Type: String
    Default: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0a481e6d13af82399"
      InstanceType: "t2.micro"
      KeyName: "EC2 Tutorial"
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: "WebSimple"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          # Install Ruby
          amazon-linux-extras install ruby3.2 -y

          mkdir -p /home/ec2-user/.metadata
          rm -f /home/ec2-user/.metadata/projectid
          echo express-demo >> /home/ec2-user/.metadata/projectid

          # Install the AWS CodeDeploy Agent
          cd /home/ec2-user/
          wget https://aws-codedeploy-ap-southeast-1.s3.amazonaws.com/releases/codedeploy-agent-1.6.0-49.noarch.rpm
          yum -y install codedeploy-agent-1.6.0-49.noarch.rpm

          curl -o- ${NvmUrl} | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install --lts

          cat <<EOF >> /home/ec2-user/.bashrc
          export NVM_DIR="/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          EOF
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: web-simple
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: Web-simple
      ComputePlatform: Server
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: MyEC2Instance
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: Web-simple-group
      ServiceRoleArn: arn:aws:iam::868133316193:role/CodeDeployServiceRole
      Ec2TagSet:
        Ec2TagSetList:
          - Ec2TagGroup:
              - Key: Name
                Value: WebSimple
                Type: KEY_AND_VALUE
