AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance

Parameters:
  SSHLocation:
    Description: IP for SSH access
    Type: String
    Default: 58.11.11.14/32
  NvmUrl:
    Description: URL for nvm install
    Type: String
    Default: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh"

Resources:
  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  MyInstanceRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyInstanceRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:Describe*
              - cloudformation:Describe*
              - cloudformation:GetTemplate
              - s3:Get*
            Resource: "*"
      Roles:
        - !Ref "MyInstanceRole"

  MyInstanceRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref "MyInstanceRole"

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0a481e6d13af82399"
      InstanceType: "t2.micro"
      IamInstanceProfile: !Ref "MyInstanceRoleInstanceProfile"
      KeyName: "EC2 Tutorial"
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: "WebSimple"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          # Install Ruby
          yum install ruby -y

          # Install the AWS CodeDeploy Agent
          cd /home/ec2-user/
          wget https://aws-codedeploy-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          rm ./install

          cat > /tmp/startup.sh << EOF
          echo "Setting up NodeJS Environment"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          . /home/ec2-user/.nvm/nvm.sh
          nvm install --lts
          EOF
          chown ec2-user:ec2-user /tmp/startup.sh && chmod a+x /tmp/startup.sh
          sleep 1; su - ec2-user -c "/tmp/startup.sh"
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: web-simple
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: Web-simple
      ComputePlatform: Server
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: MyEC2Instance
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: Web-simple-group
      ServiceRoleArn: arn:aws:iam::868133316193:role/CodeDeployServiceRole
      Ec2TagSet:
        Ec2TagSetList:
          - Ec2TagGroup:
              - Key: Name
                Value: WebSimple
                Type: KEY_AND_VALUE
