#!/bin/bash
npm_path="~/.nvm/versions/node/v18.17.0/bin/npm"
while [ ! -e "$npm_path" ]; do
    sleep 5
done
echo $PATH
cd /var/app/current
~/.nvm/versions/node/v18.17.0/bin/npm install --omit=dev
~/.nvm/versions/node/v18.17.0/bin/npm install -g pm2
