#!/bin/bash
npm_path="/home/ec2-user/.nvm/versions/node/v18.17.0/bin/npm"
while [ ! -e "$npm_path" ]; do
    sleep 10
done
PATH=/home/ec2-user/.nvm/versions/node/v18.17.0/bin:$PATH

cd /var/app/current
npm install --omit=dev
npm install -g pm2

chmod +x start-app.sh
pm2 start -f start-app.sh --name node-app
pm2 startup systemd -u ec2-user --hp /home/ec2-user
