name: Node.js CI/CD

on:
  push:
    branches: "master"

env:
  AWS_REGION: "ap-southeast-1"
  IAM_ROLE: "arn:aws:iam::868133316193:role/GitHubAction-AssumeRoleWithAction"

permissions:
  id-token: write
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Create package
        run: zip -r deploy.zip . -x "node_modules/*" -x "*.git*"

      - name: Upload to S3
        run: aws s3 cp ./deploy.zip s3://myaws-deployments/

      - name: Create AWS Infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WebSimpleStack
          template: myStack.yaml

      - name: Deploy to EC2
        id: deploy
        run: |
          deployment_id=$(aws deploy create-deployment --application-name Web-simple --deployment-group-name Web-simple-group --s3-location bucket=myaws-deployments,key=deploy.zip,bundleType=zip --query "deploymentId" --output text)
          echo "deployment-id=$deployment_id" >> $GITHUB_OUTPUT

      - name: Post-Deployment Validation
        run: |
          # Wait for deployment completion
          aws deploy wait deployment-successful --deployment-id ${{ steps.deploy.outputs.deployment-id }}
